### ISSUE TITLE
[Bug]: Append to the Dot 

### ISSUE THREAD

**Issue by sepulchra** [chrisgrieser/tot-alfred#1]
### Bug Description

⌘⏎ Append to the Dot does not append to the selected dot. It appends to the dot chosen in "quick append" selected in the user configuration.

### To Reproduce

1. select dot you want to append text to
2. ⌘⏎ Append to the Dot.
3.  enter text and hit enter. 

### Debugging Log

```Text
the debugger copies the contents of all of my tot notes so I don't want to share them here.
```

### Workflow Configuration

<img width="1196" alt="image" src="https://github.com/chrisgrieser/tot-alfred/assets/122695153/b9543802-3020-4915-a624-dd7057fd2077">

### Checklist

- [X] I have [updated to the latest version](./releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by b7aw** [comment]
Updated to 5.5, confirmed to still be an issue. Would love to append to a dot of my choosing.
